services: 
  short_term_db:
    image: timescale/timescaledb-ha:pg17
    ports:
      - ${SHORT_TERM_HOST_PORT}:5432
    environment:
      - POSTGRES_DB=${SHORT_TERM_DB}
      - POSTGRES_USER=${POSTGRESS_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - short_term_data:/home/postgres/pgdata/data
    restart: unless-stopped
  
  long_term_db:
    image: timescale/timescaledb-ha:pg17
    ports:
      - ${LONG_TERM_HOST_PORT}:5432
    environment:
      - POSTGRES_DB=${LONG_TERM_DB}
      - POSTGRES_USER=${POSTGRESS_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - long_term_data:/home/postgres/pgdata/data
    restart: unless-stopped
    
volumes:
  short_term_data:
  long_term_data: